### ISSUE TITLE
Lots of NullPointerException @ onFocusChange

### ISSUE THREAD

**Issue by carstenhag** [magnetsystems/r2m-sdk-android#5]
Repro steps video: http://youtu.be/5VyfmvlY-dM
Studio log: https://gist.github.com/Moter8/7e9d5a80b25674f96955

Using plugin version `1.1.5`, Android Studio 1.0.2 on Windows 10.

The IDE's Event tab shows these errors too. Clicking on one of them opens a window with:

```
null
java.lang.NullPointerException
    at com.magnet.plugin.ui.tab.MethodNameSection.onFocusChange(MethodNameSection.java:215)
    at com.magnet.plugin.ui.tab.URLSection.focusLost(URLSection.java:344)
    at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:230)
    at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229)
    at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229)
    at java.awt.Component.processFocusEvent(Component.java:6408)
    at java.awt.Component.processEvent(Component.java:6272)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:947)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:621)
    at java.awt.Component.dispatchEventImpl(Component.java:4742)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:713)
    at java.awt.EventQueue$4.run(EventQueue.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by etexier** [comment]
fixed in https://github.com/magnetsystems/r2m-plugin-android/releases/tag/1.1.6

**Comment by carstenhag** [comment]
Woo! :heart: :heart_decoration:

**Comment by pjaillon** [comment]
Thanks again Carsten for taking the time to provide feedback and assist Manu with this problem. We very much appreciate that.
